export const GET_MOVIES_UPCOMING = "GET_MOVIES_UPCOMING";
export const GET_MOVIES_LATEST = "GET_MOVIES_LATEST";
export const GET_MOVIES_NOW_PLAYING = "GET_MOVIES_NOW_PLAYING";
export const GET_MOVIES_POPULAR = "GET_MOVIES_POPULAR";

export const GET_MOVIE_DETAILS = "GET_MOVIES_DETAILS";
export const GET_MOVIE_TRAILERS = "GET_MOVIES_TRAILERS";
export const GET_MOVIE_CREDITS = "GET_MOVIES_CREDITS";
export const GET_MOVIE_REVIEWS = "GET_MOVIES_REVIEWS";

export const GET_CONFIG = "GET_CONFIG";
export const SEARCH_ITEMS = "SEARCH_ITEMS";
